name: Maven CLI Runner
on:
  push:
    branches: [ bshp/master ]
  pull_request:
    branches: [ bshp/master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build Package
        run: mvn -B clean package --file pom.xml
      - uses: actions/upload-artifact@v2
        with:
          name: cas
          path: target/cas.war
